# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

# Aliases are shorthand references for common settings.
aliases:
  # Branch Filtering
  - &filter-only-master
    branches:
      only:
        - master
  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages
  
# Job definitions. Job execution is orchestrated in the 'workflows' section.
jobs:
  # Build and test the Azure Functions
  build_functions:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - run:
          # A workspace allows us to pass files/artifacts from job to job.
          # https://circleci.com/blog/deep-diving-into-circleci-workspaces/
          name: Create workspace
          command: mkdir -p /tmp/workspace
      - checkout 
      - run: 
          name: Build Functions
          command: cd functions && dotnet build
      - run:
          name: Save compiled Functions to workspace
          command: cp -a functions/bin/Debug/netstandard2.0/. /tmp/workspace/publish/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - publish
  # Publish the deployment package to the Azure Function App
  publish_to_test:
    docker:
      - image: microsoft/azure-cli
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Login with Azure Service Principal
          command: az login --service-principal -u $SERVICE_PRINCIPAL_USER -p $SERVICE_PRINCIPAL_PASSWORD --tenant $SERVICE_PRINCIPAL_TENANT
      - run: 
          name: Publish Functions + SPA package to Test Function App
          command: az webapp deployment source config-zip --name $FUNCTION_APP_TEST --resource-group $FUNCTION_APP_TEST_RESOURCE_GROUP --src /tmp/workspace/publish/publish.zip
# Job orchestration
workflows:
  version: 2
  # Build and test the code on every commit. 
  # Publish the style guide on successful build/test of master.
  build-and-publish:
    jobs:
      - build_functions:
          filters: *filter-ignore-gh-pages
      - publish_to_test:
          requires:
            - build_functions
          context: azfun-fsharp
